return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "http",
        "html",
        "css",
        "scss",
        "typescript",
        "javascript",
        "tsx",
        "vue",
        "json",
        "jsonc",
        "xml",
        "yaml",
        "toml",
        "markdown",
        "bash",
        "gitignore",
        "diff",
        "c",
        "lua",
        "java",
        "go",
        "php",
        "python",
        "rust",
        "sql",
        "graphql",
        "query",
        "vim",
        "vimdoc",
      },
      highlight = { enable = true },
      indent = { enable = true },
    },
  },
}
